version: '3.4'

services:
  apiproject:
    image: ${DOCKER_REGISTRY-}apiproject
    container_name: api
    build:
      context: .
      dockerfile: ApiProject/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    networks:
      - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sapass@#SER239487"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\temp\sqlserver:/var/opt/mssql/data
    expose:
      - "1433"
    networks:
      - productnetwork

networks:
  productnetwork: